### ISSUE TITLE
Restrict bugs

### ISSUE THREAD

**Issue by prjaga** [prjaga/fireshape#1]
When trying to assign the out cofunction I'm running into some problems. 

When taking the derivative since our control is `residual` and `p0` we get a list of derivatives (as `ReducedFunctional.derivative()` takes the derivative wrt all of its controls). 

For the `residual` the type of the derivative comes as an `fd.Cofunction` while the derivative of `p0` comes as an `ufl.Coefficient`. **This already makes me think something is wrong as do we not want to derivative of p0 as a cofunction?**

The next issues comes when trying to save the cofunction value to `out.cofun`.

When doing 
`out.cofun.assign(Jhh_hat.derivative()[0])`
I get 
```Traceback (most recent call last):
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "<decorator-gen-28>", line 2, in assign
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/utils.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/cofunction.py", line 184, in assign
    return self.assign(assembled_expr, subset=subset)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "<decorator-gen-28>", line 2, in assign
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/utils.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/cofunction.py", line 184, in assign
    return self.assign(assembled_expr, subset=subset)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "<decorator-gen-28>", line 2, in assign
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/utils.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/cofunction.py", line 184, in assign
    return self.assign(assembled_expr, subset=subset)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "<decorator-gen-28>", line 2, in assign
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/utils.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/cofunction.py", line 184, in assign
    return self.assign(assembled_expr, subset=subset)
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/adjoint_utils/function.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "<decorator-gen-28>", line 2, in assign
.
.
.
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/functionspaceimpl.py", line 313, in __hash__
    return hash((self.mesh(), self.topological))
  File "/home/prem/src/firedrake/firedrake/src/ufl/ufl/core/ufl_type.py", line 38, in __hash__
    return hash(self._ufl_hash_data_())
  File "/home/prem/src/firedrake/firedrake/src/FInAT/finat/ufl/finiteelementbase.py", line 87, in __hash__
    return hash(self._ufl_hash_data_())
  File "/home/prem/src/firedrake/firedrake/src/FInAT/finat/ufl/finiteelementbase.py", line 79, in _ufl_hash_data_
    return repr(self)
RecursionError: maximum recursion depth exceeded
```

When I try and do 
`out.cofun = Jhh_hat.derivative()[0]`
the restrict function exits but I get 
```
Traceback (most recent call last):
  File "/home/prem/src/github/fireshape/examples/levelset_cm/levelset_cm.py", line 53, in <module>
    solver.solve()
  File "/home/prem/src/github/fireshape/fireshape/objective.py", line 64, in gradient
    g.apply_riesz_map()
  File "/home/prem/src/github/fireshape/fireshape/control.py", line 909, in apply_riesz_map
    self.inner_product.riesz_map(self, self)
  File "/home/prem/src/github/fireshape/fireshape/innerproduct.py", line 167, in riesz_map
    self.ls.solve(out.fun, v.cofun)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/prem/src/firedrake/firedrake/src/firedrake/firedrake/linear_solver.py", line 171, in solve
    self.ksp.solve(rhs, solution)
  File "petsc4py/PETSc/KSP.pyx", line 1711, in petsc4py.PETSc.KSP.solve
petsc4py.PETSc.Error: error code 75
[0] KSPSolve() at /home/prem/src/firedrake/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c:1082
[0] KSPSolve_Private() at /home/prem/src/firedrake/firedrake/src/petsc/src/ksp/ksp/interface/itfunc.c:910
[0] KSPSolve_BCGS() at /home/prem/src/firedrake/firedrake/src/petsc/src/ksp/ksp/impls/bcgs/bcgs.c:37
[0] KSPInitialResidual() at /home/prem/src/firedrake/firedrake/src/petsc/src/ksp/ksp/interface/itres.c:60
[0] VecCopy() at /home/prem/src/firedrake/firedrake/src/petsc/src/vec/vec/interface/vector.c:1750
[0] VecCopyAsync_Private() at /home/prem/src/firedrake/firedrake/src/petsc/src/vec/vec/interface/vector.c:1669
[0] Arguments are incompatible
[0] Incompatible vector local lengths parameter # 1 local size 1626 != parameter # 2 local size 813
```

I feel like something is somewhat correct as the adjoint calculation is completing and we are getting something which is twice the size of the vector which we need.

All the code is at:
https://github.com/prjaga/fireshape/blob/pj/newcontrolspace/fireshape/control.py#L189-L224

**Comment by colinjcotter** [comment]
Can you try interpolate instead of assign?

**Comment by colinjcotter** [comment]
Can you try wrapping the derivative in assemble()?

**Comment by prjaga** [comment]
Tried both 
`out.cofun = fd.assemble(Jhh_hat.derivative()[0])` and `out.cofun.assign(fd.assemble(Jhh_hat.derivative()[0]))` and they both had same errors as above respectively.

**Comment by prjaga** [comment]
I think the issue was the control space returns which function space should be used to calculate inner products. I was returning a vector function space here assuming it was the same as the FeControlSpace but it should have been the Scalar function space that p0 is pulled from. This also explains why the vector was twice as big as it should have been when doing the linear solve. 

```python
def get_space_for_inner(self):
        return (self.P, None)
```
